### ISSUE TITLE
Infografía de conceptos y fases de gestión de proyectos de software.

### ISSUE THREAD

**Issue by Edwin-1012** [SistemasTecTlaxiaco/infografia-Edwin-1012-1#2]
![Infografía_Edwin Bautista García](https://user-images.githubusercontent.com/72049201/132230942-0fc35046-aeae-4e81-8f5b-842509703c2b.jpg)

**Comment by CarlosSD16** [comment]
Muy buen trabajo la combinación de colores el uso de imágenes es adecuado , al igual de la presentación de la información presenta las ideas de la manera adecuada  
Calificación: 20 puntos

**Comment by josealfredo79** [comment]
Solo faltaría agregar metodologías y herramientas

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
